name: EDU Realtime CI with Maven

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: skiinder
  IMAGE: edu-realtime
  MVN_VERSION: '3.6.3'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          architecture: x64
      - name: Build with Maven
        run: mvn clean package
      - name: Build Docker Image
        run: |
          docker login \
            --username=${{ secrets.DOCKER_USERNAME }} \
            --password=${{ secrets.DOCKER_PASSWORD }} \
            ${REGISTRY}
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest